"""removed waiting time

Revision ID: 030389d488c1
Revises: 20260508_0004
Create Date: 2026-05-14 12:15:24.101041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '030389d488c1'
down_revision: Union[str, None] = '20260508_0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queue_tokens', 'estimated_wait_minutes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queue_tokens', sa.Column('estimated_wait_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###

