"""recording service time in token

Revision ID: 4f3122197651
Revises: 20260507_0003
Create Date: 2026-05-08 12:30:34.565695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4f3122197651'
down_revision: Union[str, None] = '20260507_0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queue_tokens', sa.Column('service_time_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queue_tokens', 'service_time_minutes')
    # ### end Alembic commands ###

