"""init

Revision ID: 6a025f451096
Revises: 
Create Date: 2026-05-07 17:44:24.540252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6a025f451096'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_number', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('manager_name', sa.String(length=150), nullable=True),
    sa.Column('manager_phone', sa.String(length=10), nullable=True),
    sa.Column('spoc_name', sa.String(length=150), nullable=True),
    sa.Column('spoc_phone', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stores_id'), 'stores', ['id'], unique=False)
    op.create_index(op.f('ix_stores_store_number'), 'stores', ['store_number'], unique=True)
    op.create_table('checkout_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('section_type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkout_sections_id'), 'checkout_sections', ['id'], unique=False)
    op.create_index(op.f('ix_checkout_sections_store_id'), 'checkout_sections', ['store_id'], unique=False)
    op.create_table('counters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('counter_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('next_available_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['checkout_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_counters_id'), 'counters', ['id'], unique=False)
    op.create_index(op.f('ix_counters_section_id'), 'counters', ['section_id'], unique=False)
    op.create_table('queue_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('assigned_counter_id', sa.Integer(), nullable=True),
    sa.Column('token_number', sa.String(length=30), nullable=False),
    sa.Column('phone_number', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('WAITING', 'CALLED', 'SERVING', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='queue_token_status'), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=True),
    sa.Column('basket_size', sa.String(length=50), nullable=True),
    sa.Column('cart_type', sa.String(length=50), nullable=True),
    sa.Column('customer_type', sa.String(length=50), nullable=True),
    sa.Column('is_still_shopping', sa.Boolean(), nullable=False),
    sa.Column('estimated_wait_minutes', sa.Integer(), nullable=True),
    sa.Column('calculation_method', sa.String(length=50), nullable=True),
    sa.Column('called_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('service_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_counter_id'], ['counters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['section_id'], ['checkout_sections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queue_tokens_assigned_counter_id'), 'queue_tokens', ['assigned_counter_id'], unique=False)
    op.create_index(op.f('ix_queue_tokens_id'), 'queue_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_queue_tokens_phone_number'), 'queue_tokens', ['phone_number'], unique=False)
    op.create_index(op.f('ix_queue_tokens_section_id'), 'queue_tokens', ['section_id'], unique=False)
    op.create_index(op.f('ix_queue_tokens_status'), 'queue_tokens', ['status'], unique=False)
    op.create_index(op.f('ix_queue_tokens_store_id'), 'queue_tokens', ['store_id'], unique=False)
    op.create_index(op.f('ix_queue_tokens_token_number'), 'queue_tokens', ['token_number'], unique=False)
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('assigned_counter_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('phone_number', sa.String(length=10), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_counter_id'], ['counters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['section_id'], ['checkout_sections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_assigned_counter_id'), 'staff', ['assigned_counter_id'], unique=False)
    op.create_index(op.f('ix_staff_id'), 'staff', ['id'], unique=False)
    op.create_index(op.f('ix_staff_phone_number'), 'staff', ['phone_number'], unique=False)
    op.create_index(op.f('ix_staff_section_id'), 'staff', ['section_id'], unique=False)
    op.create_index(op.f('ix_staff_store_id'), 'staff', ['store_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=10), nullable=True),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('default_role', sa.Enum('SUPER_ADMIN', 'STORE_ADMIN', 'MANAGER', 'CASHIER', 'SUPPORT', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_index(op.f('ix_users_staff_id'), 'users', ['staff_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('user_store_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'STORE_ADMIN', 'MANAGER', 'CASHIER', 'SUPPORT', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'store_id', name='uq_user_store_access_user_store')
    )
    op.create_index(op.f('ix_user_store_access_id'), 'user_store_access', ['id'], unique=False)
    op.create_index(op.f('ix_user_store_access_store_id'), 'user_store_access', ['store_id'], unique=False)
    op.create_index(op.f('ix_user_store_access_user_id'), 'user_store_access', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_store_access_user_id'), table_name='user_store_access')
    op.drop_index(op.f('ix_user_store_access_store_id'), table_name='user_store_access')
    op.drop_index(op.f('ix_user_store_access_id'), table_name='user_store_access')
    op.drop_table('user_store_access')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_users_staff_id'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_staff_store_id'), table_name='staff')
    op.drop_index(op.f('ix_staff_section_id'), table_name='staff')
    op.drop_index(op.f('ix_staff_phone_number'), table_name='staff')
    op.drop_index(op.f('ix_staff_id'), table_name='staff')
    op.drop_index(op.f('ix_staff_assigned_counter_id'), table_name='staff')
    op.drop_table('staff')
    op.drop_index(op.f('ix_queue_tokens_token_number'), table_name='queue_tokens')
    op.drop_index(op.f('ix_queue_tokens_store_id'), table_name='queue_tokens')
    op.drop_index(op.f('ix_queue_tokens_status'), table_name='queue_tokens')
    op.drop_index(op.f('ix_queue_tokens_section_id'), table_name='queue_tokens')
    op.drop_index(op.f('ix_queue_tokens_phone_number'), table_name='queue_tokens')
    op.drop_index(op.f('ix_queue_tokens_id'), table_name='queue_tokens')
    op.drop_index(op.f('ix_queue_tokens_assigned_counter_id'), table_name='queue_tokens')
    op.drop_table('queue_tokens')
    op.drop_index(op.f('ix_counters_section_id'), table_name='counters')
    op.drop_index(op.f('ix_counters_id'), table_name='counters')
    op.drop_table('counters')
    op.drop_index(op.f('ix_checkout_sections_store_id'), table_name='checkout_sections')
    op.drop_index(op.f('ix_checkout_sections_id'), table_name='checkout_sections')
    op.drop_table('checkout_sections')
    op.drop_index(op.f('ix_stores_store_number'), table_name='stores')
    op.drop_index(op.f('ix_stores_id'), table_name='stores')
    op.drop_table('stores')
    # ### end Alembic commands ###

